/*
 *  Copyright (C) 2007 Folkert J. Wijnstra
 *
 *
 *  This file is part of FMail.
 *
 *  FMail is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  FMail is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 */


//#define EDIT_NETMAIL         1
//#define EDIT_GLOB_BBS        2
#define EDIT_NODE            4
#define EDIT_NODE_DEFAULT    8
#define EDIT_NODE_GLOBAL    16
#define DISPLAY_NODE_WINDOW 32
#define DISPLAY_NODE_DATA   64

s16 nodeMgr (void);
